### ISSUE TITLE
ImportSectionEntryType does not implement clone

### ISSUE THREAD

**Issue by Others** [wasdk/wasmparser#13]
`ImportSectionEntryType` in `parser.rs` does not derive clone, but it probably should. Changing it to carry reference types would be a breaking change anyway, so no reason for it not to be cloneable. (This makes to ergonomics of the library slightly better.)

The same argument might be made for the other simple enums in the module.

**Comment by Others** [comment]
`MemoryImmediate` also has this problem

**Comment by yurydelendik** [comment]
Moved to https://github.com/yurydelendik/wasmparser.rs/issues/54
