### ISSUE TITLE
Naming of functions

### ISSUE THREAD

**Issue by bmeurer** [wasdk/wasmparser#27]
Currently we can have different names for functions, either `$func<id>`, `$imported<id>` or `$unknown<id>`. Specifically for the first two, is there a particular reason for the distinction? How about just always using `$func<id>`? Would that be okay as well?

**Comment by yurydelendik** [comment]
>  Specifically for the first two, is there a particular reason for the distinction?

Initially it was `$func<id>` only. But tools and/or browsers started adopting different automatic names schemes for WAT functions or locals.

> How about just always using $func<id>? 

`$unknown<id>` was a workaround for names section duplicates: compilers were able to generate non-unique function name. Typical issue, binaryen's `wasm-dis` generates .wast, user adds couple of unnamed functions, `wasm-as` produces name section with some out-of-order `$func` names and auto-generated names will collide with these.

**Comment by bmeurer** [comment]
> > Specifically for the first two, is there a particular reason for the distinction?
> 
> Initially it was `$func<id>` only. But tools and/or browsers started adopting different automatic names schemes for WAT functions or locals.

I don't really understand the argument for `$imported<id>` in this case. Is the goal to be compatible with a specific tool? If so, which tool is that?

> > How about just always using $func?
> 
> `$unknown<id>` was a workaround for names section duplicates: compilers were able to generate non-unique function name. Typical issue, binaryen's `wasm-dis` generates .wast, user adds couple of unnamed functions, `wasm-as` produces name section with some out-of-order `$func` names and auto-generated names will collide with these.

Does Firefox DevTools apply the same trick for the names used in the debugger / profiler?

**Comment by yurydelendik** [comment]
> Does Firefox DevTools apply the same trick for the names used in the debugger / profiler?

Profiler is using name section's data as is. The debugger uses WasmDis for text display, and does not use $name for any indexing/operation.

**Comment by bmeurer** [comment]
But what about the scope view? Doesn't that also consume the name section data?

For Chromium DevTools i'd prefer to have some kind of consistency regarding the names, meaning any kind of additional magic on top of the name section and very simple rules how to derive fallback names, should be justified. That's why I'm wondering if we could reduce the amount of magic in `WasmDis`?

**Comment by yurydelendik** [comment]
> But what about the scope view? Doesn't that also consume the name section data?

Variables are always named as `$varN` in the engine -- name section info for local is discarded atm and it is not worth to support it: it is useless since tools such clang or rustc cannot map original language variables to wasm locals IMHO.

> ... I'm wondering if we could reduce the amount of magic in WasmDis?

Agree. That's why I introduced the name resolver abstraction to wrap tooling specific naming magic in it.

I have no specific solution, except documenting (very) strict rules how devtools shall consume and display function/locals names for wasm files when name section is incomplete and/or erroneous.

**Comment by bmeurer** [comment]
So int he context of [this proposal](http://bit.ly/wasm-fallback-dx#bookmark=id.9y5zbkeekt0t), would you be fine with including a second name section reader (let's say `Wasm2WatReader`), which does the name resolution/generation according to what `wasm2wat` (aka wabt) does?

**Comment by yurydelendik** [comment]
> would you be fine with including a second name section reader ?

yes, that's preferable atm, but it can become the default one at some point.

**Comment by bmeurer** [comment]
Ok, so adding a new `WabtNameResolver` would be the way to go about this initially?

**Comment by yurydelendik** [comment]
> so adding a new WabtNameResolver would be the way to go about this initially?

yes IMHO

**Comment by bmeurer** [comment]
So now that this is fixed, how about making the `DevToolsNameResolver` the default one?

**Comment by bmeurer** [comment]
@yurydelendik Thoughts?

**Comment by yurydelendik** [comment]
It is a yes to proceed. Let's see the changes (via PR). I don't think we will see much effects in snapshot tests.
