### ISSUE TITLE
CI setup

### ISSUE THREAD

**Issue by bmeurer** [wasdk/wasmparser#46]
@yurydelendik how do you feel about setting up Travis CI (there's already `.travis.yml`?) or GitHub Actions to run the tests on pull requests and commits?

**Comment by yurydelendik** [comment]
Travis CI is running all PR atm e.g. https://travis-ci.org/github/wasdk/wasmparser/builds/689253833, and it was visible in PR at some point. There is no preference either for Travis or Actions, if there is a need we can choose the latter.

**Comment by yurydelendik** [comment]
Looks like disabling/re-enabling helped to restore the check mark in PR. Closing this issue as fixed.

**Comment by bmeurer** [comment]
Thanks!
