### ISSUE TITLE
Automatic releases and ChangeLog?

### ISSUE THREAD

**Issue by bmeurer** [wasdk/wasmparser#52]
@yurydelendik have you considered automating releases (via for example [semantic-release](https://github.com/semantic-release/semantic-release))? And especially also generating a ChangeLog based on the git commits (whose style is enforced via git hooks)? It's not strictly necessary, but it'd make change tracking easier for us, since downstream we'd just get the ChangeLog diff and could see exactly what happened in each commit?

Also it'd probably reduce the amount of manual work on your side considerably.

**Comment by yurydelendik** [comment]
I did not use tools such as semantic-release in the past. With help, I can wireup and configure proposed PRs.

Also the first step is to pass 0.x stage. Once we have plan with automatic releases, we can do a major release.

**Comment by bmeurer** [comment]
`semantic-release` has somewhat automated setup (I haven't tried that personally, but I expect it to work well, based on what other said). I can send PRs for commit message pre-checks and stuff, but you'll probably need to do the semantic-release switch: https://semantic-release.gitbook.io/semantic-release/

**Comment by yurydelendik** [comment]
Closing as fixed. It sneak-released version 1.0.0 , so we are now at version 1.0. Cheers!

**Comment by yurydelendik** [comment]
Noticed that it did not do any package.json + package-lock.json update in the github -- not sure about that.

**Comment by bmeurer** [comment]
Wow, that triggered quite a few emails 😆 
The [v1.0.0 release](https://github.com/wasdk/wasmparser/releases/tag/v1.0.0) also contains 0.16.1 as version in the package.json, so that definitely doesn't work correctly right now. 🤔

**Comment by bmeurer** [comment]
Looks like you need to setup the [semantic-release/git](https://github.com/semantic-release/git) plugin to push the `package.json` changes back to git.

**Comment by bmeurer** [comment]
There you go: https://github.com/wasdk/wasmparser/pull/55 😄
