### ISSUE TITLE
Travis CI broken again?

### ISSUE THREAD

**Issue by bmeurer** [wasdk/wasmparser#58]
@yurydelendik looks like Travis doesn't run `npm test` anymore again, for example see https://travis-ci.org/github/wasdk/wasmparser/builds/696495499 from my latest PR.

**Comment by yurydelendik** [comment]
I think it fixed itself. Please confirm.

**Comment by bmeurer** [comment]
Doesn't seem to be fixed, for example see https://travis-ci.org/github/wasdk/wasmparser/builds/696721647 from my latest push.

**Comment by bmeurer** [comment]
Interestingly Travis logs this line

```
Skipping the script step, as specified in the configuration.
```
