### ISSUE TITLE
LEB code for extensions operators

### ISSUE THREAD

**Issue by yurydelendik** [wasdk/wasmparser#76]
See WebAssembly/spec#1228 (comment): prefix is a single byte, and what follows is a LEB128

The changes in the https://github.com/WebAssembly/spec/pull/1235/files#diff-59c366fbc32de0cb02b330bf7871317f shows that we cannot just read a byte -- operator can be represented as extended LEB

**Comment by bmeurer** [comment]
@ngzhian Do you want to take a stab at this?
