### ISSUE TITLE
New (and renumbered) opcodes

### ISSUE THREAD

**Issue by yurydelendik** [wasdk/wasmparser#90]
Tracking https://github.com/WebAssembly/simd/pull/452

**Comment by yurydelendik** [comment]
https://github.com/wasdk/wasmparser/blob/master/src/WasmParser.ts#L317-L501 is using `0xfdXX` opcode format -- we probably need to extend it to something like `0xfdXXXX`

**Comment by bmeurer** [comment]
cc @ngzhian

**Comment by ngzhian** [comment]
If all goes well we won't need `0xfdXXXX` :) (v8 has the same issue too)

**Comment by ngzhian** [comment]
Confirmed, we won't need to support 0xfdXXXX!

**Comment by yurydelendik** [comment]
ref https://github.com/WebAssembly/simd/issues/480
