### ISSUE TITLE
Extract import / export type data?

### ISSUE THREAD

**Issue by gliese1337** [wasdk/wasmparser#93]
I am looking for a way to programmatically extract the complete list of imports and exports from a WASM module along with each im/export's full type signature. It looks like this library might be just what I need, but the documentation doesn't really make it obvious how that could be accomplished. Is there an easy way to do it, or do I need to keep looking elsewhere?

**Comment by yurydelendik** [comment]
Check the examples/dump-section.js , you just need to handle more states. See also https://github.com/wasdk/wasmparser/blob/648fff52d2a186fb6bee97dc1f37b97640e26fbf/src/WasmParser.ts#L1346-L1357

**Comment by yurydelendik** [comment]
Closing as anwered.
