### ISSUE TITLE
Where are tests in test/__fixtures__ generated from?

### ISSUE THREAD

**Issue by ngzhian** [wasdk/wasmparser#94]
Some of those test files (.wasm) are out of date, using older opcodes. Were they generated from somewhere?

**Comment by yurydelendik** [comment]
The .wasm files were taken from various (draft) proposals and there was a plan to retire these when final proposal will come out. So pretty much is it safe to remove one that uses older opcode or redundant to the wasm testsuite.

**Comment by ngzhian** [comment]
Thanks!
